### ISSUE TITLE
From web enabled pixel, after writing an animation (saving to the SD card), cannot change modes after that

### ISSUE THREAD

**Issue by alinke** [alinke/PIXEL#6]
Work around is to stop and re-start the .jar on the Pi. Maybe check that after writing (saving), we are still putting pixel back into interactive mode and not stuck on local playback

**Comment by alinke** [comment]
tested this one again, still there. I'm guessing pixel is stuck in local playback mode after writing. It's fine to keep in local playback mode but if the user clicks somewhere else, then just add the line to add back into interactive and that should do it

**Comment by onebeartoe** [comment]
I just checked in a fix for this issue.  Can you pull the latest and verify?

**Comment by alinke** [comment]
fixed now, thx
