### ISSUE TITLE
PIXLZ025 Not Supported

### ISSUE THREAD

**Issue by zhkfn** [alinke/PIXEL#9]
Would it be possible to add support for this device to the web app?

**Comment by alinke** [comment]
give this one a shot http://ledpixelart.com/downloads/pixelweb.jar , let me know how it goes and also if you don't mind sharing, would love to see how your project turns out. Also in case you need it, the windows app also supported PIXLZ025 now too http://ledpixelart.com/downloads/PIXEL-Setup-4-1.exe.zip

**Comment by zhkfn** [comment]
Thanks for the quick fix! I have it running successfully via Bluetooth on a Windows. Everything works perfectly except it's not able to display or save animated gifs via the web interface.

I plan to work on a user interface for our intranet that works with it.

**Comment by alinke** [comment]
very cool, shoot over some pics when you're done if you don't mind. on the animated gifs, sorry don't have the time to look into that right now

**Comment by onebeartoe** [comment]
zhkfn, I meant to chime in sooner.  Can you provide any log messages seen when the display or save animated gifs are not working?

**Comment by alinke** [comment]
I think I know the problem. The iOS/Android firmware has a problem with the gif writes but the android only firmware should work. Danielle, did you get the maker's kit or the assembled frame. If maker's kit, then you can switch to the android only firmware here http://ledpixelart.com/firmware/ . If the frame, then the firmware can't be changed on the fly unfortunately but I can send you the .hex file to flash the firmware if you've got a pickit3 programmer or you can send to me and I can do it.

**Comment by onebeartoe** [comment]
I digress.

**Comment by zhkfn** [comment]
I have an assembled frame. I can change gifs just fine with the Android app, but my husband primarily uses a mac, so I was hoping to set up a web app for him. We don't have ios, so the Android only firmware should be perfect.

If you can send me the hex file, that would be great. I'll look into getting a pickit3. Thanks for the help.

**Comment by alinke** [comment]
here you go Danielle http://ledpixelart.com/flash-firmware-with-pickit3/ , let me know how it goes

**Comment by alinke** [comment]
Hey Danielle, sorry I mis-spoke earlier on this one, actually you should be able to change firmwares via the sd card with the frame you have now, instructions here http://ledpixelart.com/firmware/
